---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders-db
  labels:
    name: orders-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
      - name: orders-db
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
          {{- if .Values.persistence.enabled }}
          - mountPath: /data/db
            name: db-volume
          {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        {{- if .Values.persistence.enabled }}
        - name: db-volume
          persistentVolumeClaim:
            claimName: orders-db
        {{- end }}
